'use strict';
const $=id=>document.getElementById(id),num=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
let updating=false;
function table(id,headers,rows){const t=document.createElement('table'),h=t.createTHead().insertRow();for(const label of headers){const c=document.createElement('th');c.textContent=label;h.append(c);}const body=t.createTBody();for(const cells of rows){const r=body.insertRow();if(id==='alert-table')r.dataset.severity=cells[0];for(const value of cells){const c=r.insertCell();c.textContent=value??'—';}}$(id).replaceChildren(t);}
function cards(id,items){$(id).replaceChildren();for(const [label,value] of items){const a=document.createElement('article'),s=document.createElement('span'),v=document.createElement('strong');s.textContent=label;v.textContent=value;a.append(s,v);$(id).append(a);}}
async function update(){if(updating)return;updating=true;try{const response=await fetch('/demo/autopilot');if(!response.ok)throw Error('Dashboard temporarily unavailable. Retrying automatically.');const d=await response.json(),a=d.autopilot,w=d.workflow,s=w.settings,crisis=a.crisis||{},plans=crisis.plans||[],hazards=crisis.hazards||{},disaster=hazards.disaster||{};$('error').textContent='';$('connection').textContent=a.enabled&&a.source_available?'AUTOMATIC DEMO':'REPLAY UNAVAILABLE';$('heartbeat').textContent=`Worker ${s.running?'running':'paused'} · replay step ${a.step} · simulation day ${crisis.simulation_day||0} (5 seconds/day) · server tick ${s.last_tick_utc||'starting'} · automatic refresh every 5 seconds`;
cards('metrics',[['Main warehouse stock',num(w.inventory.filter(r=>r.kind==='main').reduce((t,r)=>t+r.on_hand_tonnes,0))+' t'],['Regional warehouse stock',num(w.inventory.filter(r=>r.kind==='regional').reduce((t,r)=>t+r.on_hand_tonnes,0))+' t'],['Active shift alerts',d.alert_counts.ACTIVE||0],['Uncovered three-day shortfall',num(plans.reduce((t,p)=>t+p.uncovered_shortfall_tonnes,0))+' t'],['Synthetic fuel price',num(hazards.fuel_price||s.fuel_price)+' INR/litre'],['Transport status',hazards.strike_active||disaster.active?'Disrupted':disaster.early_warning?'Watch':'Routes open']]);
const active=d.alerts.filter(r=>r.status==='ACTIVE');shiftFeed(active,plans,hazards);networkCards(w.inventory);$('alert-status').textContent=`${active.length} active incidents · last scan ${d.last_alert_scan||'starting'} · synthetic demonstration alerts`;
table('alert-table',['Severity','Warehouse','Incident','Detail','State'],[...d.alerts].sort((x,y)=>(y.status==='ACTIVE')-(x.status==='ACTIVE')).slice(0,20).map(r=>[r.severity,r.warehouse_id||'Business-wide',r.title,r.detail,r.status]));$('email-status').textContent=`Email service: ${d.email_configured?'SMTP configured':'not configured yet'}. ${d.email_note} Real recorded-business alerts support automatic owner and warehouse-manager email routing after secure server setup.`;
table('inventory-table',['Warehouse','Type','Commodity','On hand (t)','Reserved (t)','Available (t)'],w.inventory.map(r=>[r.warehouse_name,r.kind,r.commodity,num(r.on_hand_tonnes),num(r.reserved_tonnes),num(r.available_tonnes)]));
$('hazard-context').textContent=`Fuel change ${num(((hazards.fuel_price||95)/95-1)*100)}% vs fixed synthetic reference. Strike: ${hazards.strike_active?'active; affected dispatches held':'inactive'}. Flood: ${disaster.active?'North route closed':disaster.early_warning?'North scenario starts in '+disaster.days_until_onset+' simulated days':'no active warning'}. All disruption inputs are synthetic; no verified disaster feed is connected.`;responseCards(plans);decisionCards(plans);table('plan-table',['Region / crop','Risk','Projected daily demand (t)','Days of cover before response','Proposed transfer (t)','Uncovered shortfall (t)','Recommendation','Evidence'],plans.map(p=>[p.region+' / '+p.commodity,p.risk,num(p.daily_demand_forecast_tonnes),num(p.cover_days_before_response),num(p.proposed_transfer_tonnes),num(p.uncovered_shortfall_tonnes),p.recommendation,p.evidence+'; '+p.reliability]));table('event-table',['UTC','Order','Event','Detail'],w.events.slice(0,15).map(r=>[r.created_utc,r.order_id,r.kind,r.detail]));
$('market-context').textContent=`Replaying ${a.source_rows} actual market observations from March 2024, then looping. Replay cycles: ${a.replay_loops}. These are historical supply arrivals and prices, not current customer demand or warehouse inventory.`;table('market-table',['Historical date','Market','Commodity','Arrivals (tonnes)','Price (INR/quintal)'],a.historical_market_rows.slice(0,15).map(r=>[r.date,r.market,r.commodity,num(r.arrivals),num(r.modal_price)]));table('forecast-table',['Historical date','Market','Commodity','Forecast (t)','95% interval (t)','Actual (t)','Review'],a.historical_market_rows.slice(0,8).map(r=>{const f=r.forecast;return[r.date,r.market,r.commodity,f?num(f.prediction):'Unavailable',f?num(f.interval.lower)+' – '+num(f.interval.upper):r.forecast_error,num(r.arrivals),f?f.reliability.status:'Insufficient history'];}));const l=a.logistics_context;$('logistics-context').textContent=l.trips?`${num(l.trips)} historical Delhivery trips (${l.start}–${l.end}). Median actual transit ${num(l.median_actual_minutes)} minutes; median distance ${num(l.median_distance_km)} km. These trips are not joined to the synthetic orders.`:'Historical logistics context unavailable.';
const r=a.research_results;cards('research-metrics',[['Forward WAPE',r.wape_pct+'%'],['MAE',r.mae_tonnes+' tonnes'],['95% interval coverage',r.coverage_pct+'%']]);
}catch(e){$('connection').textContent='RECONNECTING';$('error').textContent=e.message;}finally{updating=false;}}
update();setInterval(update,5000);

function responseCards(plans){$('response-summary').replaceChildren();for(const region of [...new Set(plans.map(p=>p.region))]){const group=plans.filter(p=>p.region===region),a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p'),q=document.createElement('p');h.textContent=region+' regional warehouse';const worst=group.find(p=>p.risk==='HIGH')||group.find(p=>p.risk==='WATCH')||group[0];p.textContent=worst?worst.recommendation:'Monitoring';q.textContent='Proposed main-to-region transfer: '+num(group.reduce((t,p)=>t+p.proposed_transfer_tonnes,0))+' tonnes. Uncovered stress shortfall: '+num(group.reduce((t,p)=>t+p.uncovered_shortfall_tonnes,0))+' tonnes. Synthetic response only.';a.append(h,p,q);$('response-summary').append(a);}}

function decisionCards(plans){const host=$('decision-options');host.replaceChildren();for(const plan of plans.filter(p=>p.shortfall_tonnes>0||p.main_stock_out||p.main_backup_below_reserve||p.route_blocked||p.demand_surge)){const section=document.createElement('details'),h=document.createElement('summary'),context=document.createElement('p'),grid=document.createElement('div');h.textContent=plan.region+' / '+plan.commodity+' — '+plan.decision_gate;context.textContent='Main available: '+num(plan.main_available_before_response)+' t · '+(plan.main_stock_out?'MAIN STOCK-OUT':plan.main_backup_below_reserve?'LOW MAIN BACKUP':'Main backup available')+' · '+(plan.demand_surge?'Demand surge · ':'')+'Regional stress shortfall: '+num(plan.shortfall_tonnes)+' t';grid.className='option-grid';for(const o of plan.response_options||[]){const card=document.createElement('article'),title=document.createElement('h4'),badge=document.createElement('strong'),detail=document.createElement('p'),why=document.createElement('p');card.className='solution-option';card.dataset.status=o.status;title.textContent=o.title;badge.textContent=o.status+' · '+o.gate+' · Score '+num(o.score)+'/100';detail.textContent='Planning quantity: '+num(o.quantity_tonnes)+' t · '+(o.id==='ration_stock'?'Mitigation target; no stock added':num(o.shortfall_coverage_pct)+'% of stress shortfall');why.textContent=o.reason;card.append(title,badge,detail,why);grid.append(card);}section.className='incident-assessment';section.append(h,context,grid);host.append(section);}if(!host.children.length){host.textContent='No product crisis currently needs a response. Automatic monitoring continues.';}}

function networkCards(inventory){const warehouses=[...new Set(inventory.map(r=>r.warehouse_name))];cards('network-summary',warehouses.map(name=>[name,num(inventory.filter(r=>r.warehouse_name===name).reduce((t,r)=>t+r.available_tonnes,0))+' t available']));}
function shiftFeed(alerts,plans,hazards){const host=$('shift-feed');host.replaceChildren();const signals=[];if(plans.some(p=>p.main_stock_out))signals.push(['CRITICAL','Main warehouse stock-out','One or more products have no available main stock. Assess backup capacity and demand before responding.']);if(hazards.demand_surge)signals.push(['WARNING','Demand shift detected','Synthetic Southern regional demand is above its usual scenario level.']);if(hazards.fuel_price>=104.5)signals.push(['WARNING','Fuel-cost shift detected','Synthetic fuel price is '+num((hazards.fuel_price/95-1)*100)+'% above its fixed baseline.']);if(hazards.strike_active)signals.push(['CRITICAL','Transport strike scenario','Affected dispatches are held.']);if(hazards.disaster?.active||hazards.disaster?.early_warning)signals.push(['CRITICAL',hazards.disaster.active?'Flood route closure':'Flood early-warning scenario','North regional route requires attention. This is an injected scenario.']);for(const a of alerts.slice(0,4))signals.push([a.severity,a.title,a.detail]);if(!signals.length){const p=document.createElement('p');p.className='clear-status';p.textContent='No active shift alerts. Stock and transport conditions are being monitored automatically.';host.append(p);}for(const [severity,title,detail] of signals){const card=document.createElement('article'),badge=document.createElement('span'),h=document.createElement('h3'),p=document.createElement('p'),a=document.createElement('a');card.className='shift-alert';card.dataset.severity=severity;badge.textContent=severity+' · SIMULATED';h.textContent=title;p.textContent=detail;a.href='#responses';a.textContent='View assessment and solutions →';card.append(badge,h,p,a);host.append(card);}}
function showView(){const requested=location.hash.slice(1)||'home',allowed=['home','alerts','warehouses','responses','markets','evidence'],view=allowed.includes(requested)?requested:'home';for(const section of document.querySelectorAll('[data-view]'))section.hidden=section.id!==view;for(const link of document.querySelectorAll('aside nav a')){if(link.hash==='#'+view)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}const titles={home:['Supply-chain overview','Your warehouse network, stock position and emerging disruptions in one place.'],alerts:['Supply-chain shift alerts','Automatic warnings for changing stock, demand and transport conditions.'],warehouses:['Warehouse inventory','Available stock across your main and regional warehouses.'],responses:['Decision centre','Assess affected products and compare feasible responses.'],markets:['Market insights','Historical observations and forecasts for supply conditions.'],evidence:['Research evidence','Datasets, measured results and model limitations.']};$('page-title').textContent=titles[view][0];$('page-description').textContent=titles[view][1];}
showView();window.addEventListener('hashchange',showView);
