'use strict';
const $=id=>document.getElementById(id),num=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
let updating=false;
function table(id,headers,rows){const t=document.createElement('table'),h=t.createTHead().insertRow();for(const label of headers){const c=document.createElement('th');c.textContent=label;h.append(c);}const body=t.createTBody();for(const cells of rows){const r=body.insertRow();if(id==='alert-table')r.dataset.severity=cells[0];for(const value of cells){const c=r.insertCell();c.textContent=value??'—';}}$(id).replaceChildren(t);}
function cards(id,items){$(id).replaceChildren();for(const [label,value] of items){const a=document.createElement('article'),s=document.createElement('span'),v=document.createElement('strong');s.textContent=label;v.textContent=value;a.append(s,v);$(id).append(a);}}
async function update(){if(updating)return;updating=true;try{const response=await fetch('/demo/autopilot');if(!response.ok)throw Error('Dashboard temporarily unavailable. Retrying automatically.');const d=await response.json(),a=d.autopilot,w=d.workflow,s=w.settings,crisis=a.crisis||{},plans=crisis.plans||[],hazards=crisis.hazards||{},disaster=hazards.disaster||{};$('error').textContent='';$('connection').textContent=a.enabled&&a.source_available?'AUTOMATIC DEMO':'REPLAY UNAVAILABLE';$('heartbeat').textContent=`Worker ${s.running?'running':'paused'} · replay step ${a.step} · simulation day ${crisis.simulation_day||0} (5 seconds/day) · server tick ${s.last_tick_utc||'starting'} · automatic refresh every 5 seconds`;
cards('metrics',[['Main warehouse stock',num(w.inventory.filter(r=>r.kind==='main').reduce((t,r)=>t+r.on_hand_tonnes,0))+' t'],['Regional warehouse stock',num(w.inventory.filter(r=>r.kind==='regional').reduce((t,r)=>t+r.on_hand_tonnes,0))+' t'],['Active manager alerts',d.alert_counts.ACTIVE||0],['Uncovered three-day shortfall',num(plans.reduce((t,p)=>t+p.uncovered_shortfall_tonnes,0))+' t'],['Synthetic fuel price',num(hazards.fuel_price||s.fuel_price)+' INR/litre'],['Flood scenario',disaster.active?'Route closure':disaster.early_warning?'Early warning':'No active scenario']]);
const active=d.alerts.filter(r=>r.status==='ACTIVE');$('alert-status').textContent=`${active.length} active incidents · last scan ${d.last_alert_scan||'starting'} · synthetic demonstration alerts`;
table('alert-table',['Severity','Warehouse','Incident','Detail','State'],[...d.alerts].sort((x,y)=>(y.status==='ACTIVE')-(x.status==='ACTIVE')).slice(0,20).map(r=>[r.severity,r.warehouse_id||'Business-wide',r.title,r.detail,r.status]));$('email-status').textContent=`Email service: ${d.email_configured?'SMTP configured':'not configured yet'}. ${d.email_note} Real recorded-business alerts support automatic owner and warehouse-manager email routing after secure server setup.`;
table('inventory-table',['Warehouse','Type','Commodity','On hand (t)','Reserved (t)','Available (t)'],w.inventory.map(r=>[r.warehouse_name,r.kind,r.commodity,num(r.on_hand_tonnes),num(r.reserved_tonnes),num(r.available_tonnes)]));
$('hazard-context').textContent=`Fuel change ${num(((hazards.fuel_price||95)/95-1)*100)}% vs fixed synthetic reference. Strike: ${hazards.strike_active?'active; affected dispatches held':'inactive'}. Flood: ${disaster.active?'North route closed':disaster.early_warning?'North scenario starts in '+disaster.days_until_onset+' simulated days':'no active warning'}. All disruption inputs are synthetic; no verified disaster feed is connected.`;responseCards(plans);table('plan-table',['Region / crop','Risk','Projected daily demand (t)','Days of cover before response','Proposed transfer (t)','Uncovered shortfall (t)','Recommendation','Evidence'],plans.map(p=>[p.region+' / '+p.commodity,p.risk,num(p.daily_demand_forecast_tonnes),num(p.cover_days_before_response),num(p.proposed_transfer_tonnes),num(p.uncovered_shortfall_tonnes),p.recommendation,p.evidence+'; '+p.reliability]));table('event-table',['UTC','Order','Event','Detail'],w.events.slice(0,15).map(r=>[r.created_utc,r.order_id,r.kind,r.detail]));
$('market-context').textContent=`Replaying ${a.source_rows} actual market observations from March 2024, then looping. Replay cycles: ${a.replay_loops}. These are historical supply arrivals and prices, not current customer demand or warehouse inventory.`;table('market-table',['Historical date','Market','Commodity','Arrivals (tonnes)','Price (INR/quintal)'],a.historical_market_rows.slice(0,15).map(r=>[r.date,r.market,r.commodity,num(r.arrivals),num(r.modal_price)]));table('forecast-table',['Historical date','Market','Commodity','Forecast (t)','95% interval (t)','Actual (t)','Review'],a.historical_market_rows.slice(0,8).map(r=>{const f=r.forecast;return[r.date,r.market,r.commodity,f?num(f.prediction):'Unavailable',f?num(f.interval.lower)+' – '+num(f.interval.upper):r.forecast_error,num(r.arrivals),f?f.reliability.status:'Insufficient history'];}));const l=a.logistics_context;$('logistics-context').textContent=l.trips?`${num(l.trips)} historical Delhivery trips (${l.start}–${l.end}). Median actual transit ${num(l.median_actual_minutes)} minutes; median distance ${num(l.median_distance_km)} km. These trips are not joined to the synthetic orders.`:'Historical logistics context unavailable.';
const r=a.research_results;cards('research-metrics',[['Forward WAPE',r.wape_pct+'%'],['MAE',r.mae_tonnes+' tonnes'],['95% interval coverage',r.coverage_pct+'%']]);
}catch(e){$('connection').textContent='RECONNECTING';$('error').textContent=e.message;}finally{updating=false;}}
update();setInterval(update,5000);

function responseCards(plans){$('response-summary').replaceChildren();for(const region of [...new Set(plans.map(p=>p.region))]){const group=plans.filter(p=>p.region===region),a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p'),q=document.createElement('p');h.textContent=region+' regional warehouse';const worst=group.find(p=>p.risk==='HIGH')||group.find(p=>p.risk==='WATCH')||group[0];p.textContent=worst?worst.recommendation:'Monitoring';q.textContent='Proposed main-to-region transfer: '+num(group.reduce((t,p)=>t+p.proposed_transfer_tonnes,0))+' tonnes. Uncovered stress shortfall: '+num(group.reduce((t,p)=>t+p.uncovered_shortfall_tonnes,0))+' tonnes. Synthetic response only.';a.append(h,p,q);$('response-summary').append(a);}}
