'use strict';
const $=id=>document.getElementById(id),num=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});let warehouses=[],series=[];
async function api(path,body){const headers={};if($('key').value)headers['X-API-Key']=$('key').value;if(body)headers['Content-Type']='application/json';const r=await fetch(path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d;}
async function task(button,fn){$('error').textContent='';button.disabled=true;try{await fn();}catch(e){$('error').textContent=e.message;}finally{button.disabled=false;}}
function table(target,headers,rows){const t=document.createElement('table'),h=t.createTHead().insertRow();headers.forEach(v=>{const c=document.createElement('th');c.textContent=v;h.append(c);});const b=t.createTBody();rows.forEach(row=>{const r=b.insertRow();row.forEach(v=>r.insertCell().textContent=v??'—');});$(target).replaceChildren(t);}
function cards(target,items){$(target).replaceChildren();items.forEach(([label,value,unit])=>{const a=document.createElement('article'),s=document.createElement('span'),v=document.createElement('strong'),u=document.createElement('small');s.textContent=label;v.textContent=num(value);u.textContent=unit;a.append(s,v,u);$(target).append(a);});}
function form(id,fields,buttonText,submit){const f=$(id);fields.forEach(([name,label,type,values])=>{const l=document.createElement('label');l.textContent=label;const e=document.createElement(type==='select'?'select':'input');e.name=name;e.id=id+'-'+name;if(type==='select'){values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v||'None';e.append(o);});}else{e.type=type;if(type==='number'){e.step='any';e.min='0';}if(values!==undefined)e.value=values;}if(!['parent_id','destination_id','commodity_optional'].includes(name))e.required=true;l.append(e);f.append(l);});const b=document.createElement('button');b.type='submit';b.textContent=buttonText;f.append(b);f.onsubmit=e=>{e.preventDefault();task(b,()=>submit(Object.fromEntries(new FormData(f))));};}
const crops=['Rice','Wheat','Onion','Potato'];
form('warehouse-form',[['id','Warehouse ID','text'],['name','Warehouse name','text'],['kind','Type','select',['main','regional']],['region','Region','text'],['capacity_tonnes','Capacity (tonnes)','number'],['parent_id','Main warehouse ID (regional only)','text']],'Create warehouse',async d=>{d.capacity_tonnes=Number(d.capacity_tonnes);d.parent_id=d.parent_id||null;await api('/v1/operations/warehouses',d);await refresh();});
form('movement-form',[['request_id','Unique request ID','text',crypto.randomUUID()],['warehouse_id','Source warehouse ID','text'],['commodity','Commodity','select',crops],['kind','Movement','select',['receipt','dispatch','transfer']],['tonnes','Quantity (tonnes)','number'],['destination_id','Destination ID (transfers only)','text'],['reference','Record reference','text']],'Record movement',async d=>{d.tonnes=Number(d.tonnes);d.destination_id=d.destination_id||null;const r=await api('/v1/operations/movements',d);$('movement-note').textContent=r.unchanged?'Already recorded; inventory unchanged.':'Movement recorded successfully.';$('movement-form-request_id').value=crypto.randomUUID();await refresh();});
form('signal-form',[['kind','Condition','select',['demand','fuel','strike']],['region','Region','text'],['commodity_optional','Commodity (required for demand)','select',['',...crops]],['start','Starts','date',new Date().toISOString().slice(0,10)],['end','Ends','date',new Date().toISOString().slice(0,10)],['value','Value in stated units','number'],['basis','Evidence type','select',['scenario','recorded']],['source','Source / assumption reference','text']],'Save condition',async d=>{d.value=Number(d.value);d.commodity=d.commodity_optional||null;delete d.commodity_optional;await api('/v1/operations/signals',d);await refresh();});
form('plan-form',[['warehouse_id','Regional warehouse ID','text'],['commodity','Commodity','select',crops],['as_of','Plan reference date','date',new Date().toISOString().slice(0,10)],['horizon_days','Horizon (days)','number',7],['demand_tonnes_daily','Baseline demand (tonnes/day)','number'],['demand_change_pct','Demand change (%)','number',0],['strike_days','Strike days','number',0],['strike_fraction','Transport disrupted (0–1)','number',0],['distance_km','One-way distance (km)','number'],['litres_per_100km','Fuel consumption (L/100 km)','number'],['fuel_price_inr_litre','Scenario fuel price (INR/L)','number'],['baseline_fuel_price','Baseline fuel price (INR/L)','number'],['truck_capacity_tonnes','Truck capacity (tonnes)','number']],'Evaluate scenario',async d=>{for(const k of Object.keys(d))if(!['warehouse_id','commodity','as_of'].includes(k))d[k]=Number(d[k]);const r=await api('/v1/operations/plan',d);cards('plan-cards',[['Current inventory',r.inventory_tonnes,'tonnes'],['Days of cover',r.days_of_cover,'days at adjusted demand'],['Horizon demand',r.horizon_demand_tonnes,'tonnes'],['Suggested parent transfer',r.suggested_transfer_tonnes,'tonnes · review required'],['Remaining gap',r.residual_gap_tonnes,'tonnes'],['Fuel cost',r.fuel_cost_inr,'INR · fuel only'],['Fuel cost change',r.fuel_cost_change_inr,'INR versus baseline'],['Truck trips',r.truck_trips,'round trips'],['Transport availability',r.transport_availability_factor*100,'% under entered assumption']]);$('plan-assumptions').textContent=r.basis+' '+r.assumptions.join(' ')+' Saved run: '+r.id;});
$('plan-form-demand_change_pct').min='-100';
async function refresh(){const d=await api('/v1/operations/inventory');warehouses=d.warehouses;table('inventory-table',['Warehouse','Type','Region','Parent','Stock by commodity','Total / capacity (t)','Utilization'],warehouses.map(w=>[w.name+' ['+w.id+']',w.kind,w.region,w.parent_id,w.stock.map(s=>s.commodity+': '+num(s.tonnes)+' t').join(' · ')||'No stock recorded',num(w.total_tonnes)+' / '+num(w.capacity_tonnes),num(w.utilization*100)+'%']));$('inventory-note').textContent=warehouses.length?d.basis:'No warehouse records yet. Create a main warehouse, then its regional warehouses, and record opening-stock receipts.';table('ledger',['Recorded UTC','Movement','Commodity','Tonnes','Route','Reference'],d.recent_movements.map(r=>{const p=JSON.parse(r.payload);return [r.created_utc,p.kind,p.commodity,num(p.tonnes),p.warehouse_id+(p.destination_id?' → '+p.destination_id:''),p.reference];}));const s=await api('/v1/operations/signals');table('signals-table',['Condition','Region','Commodity','Dates','Value','Basis','Source'],s.signals.map(r=>[r.kind,r.region,r.commodity,r.start+' → '+r.end,r.value,r.basis,r.source]));const c=await api('/v1/catalog');series=c.series;$('market-series').replaceChildren();series.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.market+' · '+r.commodity;$('market-series').append(o);});}
$('connect').onclick=()=>task($('connect'),refresh);$('market-button').onclick=()=>task($('market-button'),async()=>{const s=series[Number($('market-series').value)];if(!s)throw Error('Import market observations in the forecast workspace first.');const q=new URLSearchParams({state:s.state,market:s.market,commodity:s.commodity,as_of:$('market-date').value});const r=await api('/v1/operations/market?'+q);cards('market-cards',[['Recent modal price',r.price_inr_quintal.recent_mean,'INR/quintal'],['Price change',r.price_inr_quintal.change_pct,'% versus preceding seven days'],['Arrival change',r.arrivals_tonnes.change_pct,'% · inflow, not demand']]);$('market-note').textContent=`${r.basis} Last record: ${r.last_recorded_date}. Reports: ${r.recent_reports} recent / ${r.previous_reports} previous.`;});task($('connect'),refresh);
